from __future__ import annotations

r"""
setup_oracle_demo_schema.py

Reusable schema setup script for the standalone ordb_project_exai Oracle demo
project.

Purpose:
    Create the baseline demo tables for the Oracle user configured in .env.

This script is portable:
    - It does not hardcode DEVUSER.
    - It creates tables in the currently connected ORACLE_USER schema.
    - It supports the quoted table name "My Favorite saying".

Run from project root:

    cd C:\Users\cetax\PycharmProjects\ordb_project_exai

Dry run first:

    python .\tests_scripts\setup_oracle_demo_schema.py

Create missing tables and seed sample data:

    python .\tests_scripts\setup_oracle_demo_schema.py --execute

Drop/recreate baseline demo tables and seed sample data:

    python .\tests_scripts\setup_oracle_demo_schema.py --execute --drop-existing

Create tables without seed data:

    python .\tests_scripts\setup_oracle_demo_schema.py --execute --no-seed

Reseed existing tables:

    python .\tests_scripts\setup_oracle_demo_schema.py --execute --reseed

Important:
    This script is intended for a demo database.
"""

import argparse
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any


# ------------------------------------------------------------
# Add project root to sys.path BEFORE importing from app.
# ------------------------------------------------------------
PROJECT_ROOT = Path(__file__).resolve().parents[1]

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))


from app.models.configuration.oracle_config import get_oracle_config
from app.models.service import OracleQueryService, OracleSchemaService


@dataclass(frozen=True)
class DemoTableDefinition:
    table_name: str
    create_sql: str


@dataclass(frozen=True)
class DemoSeedRow:
    table_name: str
    insert_sql: str
    binds: dict[str, Any]


DEMO_TABLES: list[DemoTableDefinition] = [
    DemoTableDefinition(
        table_name="COLOUR",
        create_sql="""
        CREATE TABLE "COLOUR" (
            ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            NAME VARCHAR2(50) NOT NULL,
            HEX_CODE VARCHAR2(7),
            CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
            ABBR VARCHAR2(3) NOT NULL
        )
        """,
    ),
    DemoTableDefinition(
        table_name="My Favorite saying",
        create_sql="""
        CREATE TABLE "My Favorite saying" (
            ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            SAYING VARCHAR2(4000) NOT NULL,
            CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
        )
        """,
    ),
]


DEMO_SEED_ROWS: list[DemoSeedRow] = [
    DemoSeedRow(
        table_name="COLOUR",
        insert_sql="""
        INSERT INTO "COLOUR" (NAME, HEX_CODE, ABBR)
        VALUES (:name, :hex_code, :abbr)
        """,
        binds={"name": "Red", "hex_code": "#FF0000", "abbr": "RED"},
    ),
    DemoSeedRow(
        table_name="COLOUR",
        insert_sql="""
        INSERT INTO "COLOUR" (NAME, HEX_CODE, ABBR)
        VALUES (:name, :hex_code, :abbr)
        """,
        binds={"name": "Blue", "hex_code": "#0000FF", "abbr": "BLU"},
    ),
    DemoSeedRow(
        table_name="COLOUR",
        insert_sql="""
        INSERT INTO "COLOUR" (NAME, HEX_CODE, ABBR)
        VALUES (:name, :hex_code, :abbr)
        """,
        binds={"name": "Yellow", "hex_code": "#FFFF00", "abbr": "YEL"},
    ),
    DemoSeedRow(
        table_name="My Favorite saying",
        insert_sql="""
        INSERT INTO "My Favorite saying" (SAYING)
        VALUES (:saying)
        """,
        binds={"saying": "AI can write to quoted Oracle tables"},
    ),
]


def print_section(title: str) -> None:
    print("\n" + "=" * 80)
    print(title)
    print("=" * 80)


def quote_oracle_identifier(identifier: str) -> str:
    if identifier is None:
        raise ValueError("Oracle identifier cannot be None.")

    clean_identifier = str(identifier).strip()

    if not clean_identifier:
        raise ValueError("Oracle identifier cannot be blank.")

    if '"' in clean_identifier:
        raise ValueError(
            f'Unsafe Oracle identifier contains double quote: {identifier}'
        )

    return f'"{clean_identifier}"'


def table_exists(
    query_service: OracleQueryService,
    table_name: str,
) -> bool:
    result = query_service.run_select(
        """
        SELECT
            table_name
        FROM user_tables
        WHERE table_name = :table_name
           OR table_name = UPPER(:table_name)
        """,
        binds={"table_name": table_name},
        max_rows=1,
    )

    return result.success and result.row_count > 0


def drop_table_if_exists(
    query_service: OracleQueryService,
    table_name: str,
) -> None:
    if not table_exists(query_service, table_name):
        print(f"Drop skipped: {table_name} does not exist.")
        return

    quoted_table_name = quote_oracle_identifier(table_name)

    result = query_service.run_sql(
        f"DROP TABLE {quoted_table_name} CASCADE CONSTRAINTS PURGE"
    )

    print(f"Drop {quoted_table_name}: success={result.success}")

    if not result.success:
        print(f"  Error: {result.error}")


def create_table_if_missing(
    query_service: OracleQueryService,
    table_definition: DemoTableDefinition,
) -> None:
    if table_exists(query_service, table_definition.table_name):
        print(f"Create skipped: {table_definition.table_name} already exists.")
        return

    result = query_service.run_sql(table_definition.create_sql)

    print(f"Create {table_definition.table_name}: success={result.success}")

    if not result.success:
        print(f"  Error: {result.error}")


def delete_seed_data(
    query_service: OracleQueryService,
) -> None:
    """
    Delete seed rows from baseline tables.

    This is used by --reseed after tables exist.
    """
    for table_definition in reversed(DEMO_TABLES):
        if not table_exists(query_service, table_definition.table_name):
            continue

        quoted_table_name = quote_oracle_identifier(table_definition.table_name)

        result = query_service.run_sql(f"DELETE FROM {quoted_table_name}")

        print(f"Delete rows from {quoted_table_name}: success={result.success}")

        if not result.success:
            print(f"  Error: {result.error}")


def seed_data(
    query_service: OracleQueryService,
) -> None:
    for seed_row in DEMO_SEED_ROWS:
        if not table_exists(query_service, seed_row.table_name):
            print(f"Seed skipped: {seed_row.table_name} does not exist.")
            continue

        result = query_service.run_sql(
            seed_row.insert_sql,
            binds=seed_row.binds,
        )

        print(f"Seed {seed_row.table_name}: success={result.success}")

        if not result.success:
            print(f"  Error: {result.error}")


def print_current_tables(
    schema_service: OracleSchemaService,
    owner: str,
) -> None:
    result = schema_service.list_accessible_tables(
        owner=owner,
        max_rows=500,
    )

    print_section(f"Tables visible for {owner}")

    if not result.success:
        print(f"Unable to list tables: {result.error}")
        return

    if not result.rows:
        print("No tables found.")
        return

    for row in result.rows:
        print(f"- {row.get('table_name')}")


def print_schema_summary(
    schema_service: OracleSchemaService,
    owner: str,
) -> None:
    summary = schema_service.build_schema_summary(
        owner=owner,
        max_tables=50,
        include_sample_rows=True,
        sample_row_count=3,
    )

    print_section("Schema summary")

    print(f"Success: {summary.get('success')}")
    print(f"Owner: {summary.get('owner_filter')}")
    print(f"Table count: {summary.get('table_count')}")
    print(f"Error: {summary.get('error')}")

    for table in summary.get("tables", []):
        print()
        print(f"Table: {table.get('table_name')}")
        print(f"Actual row count: {table.get('actual_row_count')}")
        print(f"Column count: {len(table.get('columns', []))}")
        print(f"Primary keys: {table.get('primary_keys')}")
        print(f"Sample rows: {table.get('sample_rows')}")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Create baseline Oracle demo schema objects."
    )

    parser.add_argument(
        "--execute",
        action="store_true",
        help="Actually create/seed tables. Without this flag, this is a dry run.",
    )

    parser.add_argument(
        "--drop-existing",
        action="store_true",
        help="Drop baseline demo tables before recreating them.",
    )

    parser.add_argument(
        "--no-seed",
        action="store_true",
        help="Create tables only. Do not insert sample data.",
    )

    parser.add_argument(
        "--reseed",
        action="store_true",
        help="Delete rows from baseline tables and insert fresh sample data.",
    )

    args = parser.parse_args()

    config = get_oracle_config()
    query_service = OracleQueryService()
    schema_service = OracleSchemaService()

    owner = config.oracle_user.upper()

    print_section("Oracle demo schema setup")
    print(f"Project root: {config.project_root}")
    print(f"Environment: {config.app_env}")
    print(f"Connected Oracle user from .env: {owner}")
    print(f"DSN: {config.oracle_dsn}")

    print_current_tables(schema_service, owner)

    print_section("Planned baseline tables")
    for table_definition in DEMO_TABLES:
        exists_text = "exists" if table_exists(query_service, table_definition.table_name) else "missing"
        print(f"- {table_definition.table_name}: {exists_text}")

    if not args.execute:
        print("\nDRY RUN ONLY.")
        print("No database changes were made.")
        print("\nTo create the baseline schema, run:")
        print(r"python .\tests_scripts\setup_oracle_demo_schema.py --execute")
        return

    print_section("Execute setup")

    if args.drop_existing:
        print("Drop-existing mode enabled.")
        for table_definition in reversed(DEMO_TABLES):
            drop_table_if_exists(query_service, table_definition.table_name)

    for table_definition in DEMO_TABLES:
        create_table_if_missing(query_service, table_definition)

    if args.reseed:
        print("\nReseed mode enabled.")
        delete_seed_data(query_service)

    if args.no_seed:
        print("\nSeed skipped because --no-seed was provided.")
    else:
        seed_data(query_service)

    print_current_tables(schema_service, owner)
    print_schema_summary(schema_service, owner)

    print_section("Setup complete")


if __name__ == "__main__":
    main()
